---
title: "Mini-Project 4"
author: "Emily Liu, Karina Lieb, and Alexis Kilayko"
date: "April 28, 2018"
output: html_document
---
```{r}
# Load libraries
library(mdsr)
library(RMySQL)
library(leaflet)
library(sf)
library(tidyverse)
#connecting to server
db <- dbConnect_scidb(dbname = "citibike")

```

```{r}
#NOT IN USE
test_set <- db %>%
          dbGetQuery("SELECT * 
             FROM trips
             LIMIT 100;")
test_set

test_stations <- db %>%
  dbGetQuery("SELECT *
             FROM station_months;")

test_stations %>%
  distinct(station_id) %>%
  arrange(station_id)
```

```{r}
#NOT IN USE
# Top 10 stations overall
test_set %>%
  arrange(start_station_id)
test_set %>% 
  select(start_station_id) %>%
  group_by(start_station_id) %>%
  summarize(N = n()) %>%
  arrange(desc(N)) %>%
  head(10)
  
```

```{r}
#NOT IN USE
# Top 10 stations for women
women_10 <- test_set %>% 
  filter(gender == 2) %>%
  select(start_station_id) %>%
  group_by(start_station_id) %>%
  summarize(N = n()) %>%
  arrange(desc(N)) %>%
  head(10)

# Top 10 stations for subscribers
test_set %>% 
  filter(user_type == 'Subscriber') %>%
  select(start_station_id) %>%
  group_by(start_station_id) %>%
  summarize(N = n()) %>%
  arrange(desc(N)) %>%
  head(10)
```

```{r}
#NOT IN USE
top_10_women <- women_10 %>%
  left_join(test_stations_sum, by = c("start_station_id" = "station_id"))

View(top_10_women)
```

```{r}
#NOT IN USE
#finding top 10 start stations overall
db %>%
  dbGetQuery("
SELECT trips.start_station_id,  ss.name, ss.lat, ss.lon, sum(1) AS N
FROM citibike.trips
JOIN citibike.station_summary ss ON trips.start_station_id = ss.station_id
GROUP BY trips.start_station_id
ORDER BY N desc
LIMIT 10;")

#finding top 10 start stations visited by women
db %>%
  dbGetQuery("
SELECT trips.start_station_id,  ss.name, ss.lat, ss.lon, sum(1) AS N
FROM citibike.trips
JOIN citibike.station_summary ss ON trips.start_station_id = ss.station_id
WHERE gender = 2
GROUP BY trips.start_station_id
ORDER BY N desc
LIMIT 10;")
```

```{r}
#NOT IN USE
# Points for overall start stations
all_start_pts <- tribble (
  ~name, ~lat, ~lon,
  "Pershing Square North", -73.97771, 40.75187,
  "E 17 St & Broadway", -73.99009, 40.73705,
  "Broadway & E 22 St", -73.98955, 40.74034,
  "W 21 St & 6 Ave", -73.99416, 40.74174,
  "West St & Chambers St", -74.01322, 40.71755,
  "8 Ave & W 31 St", -73.99468, 40.75059,
  "8 Ave & W 33 St", -73.99393, 40.75155,
  "W 20 St & 11 Ave", -74.00776, 40.74674,
  "12 Ave & W 40 St", -74.00278, 40.76088,
  "W 41 St & 8 Ave", -73.99003, 40.75461
)

all_start_sf <- all_start_pts %>%
  st_as_sf(coords = c("lat", "lon")) %>%
  st_set_crs(4326)

leaflet() %>%
  addTiles() %>%
  addMarkers(data = all_start_sf, popup = ~name)
```


```{r}
#finding top 10 most visited stations for everyone
everyone_visits <- db %>%
  dbGetQuery("
SELECT name, lat, lon, num_starts + num_stops AS visits
FROM citibike.station_summary ss
ORDER BY visits desc
LIMIT 10;")
```

```{r}
#station_summary table from database -- only selecting columns we need
station_summary <- db %>%
  dbGetQuery("SELECT station_id, name, lat, lon
             FROM station_summary;")

#this function takes in a demographic type and outputs one table that is the 10 most visited (start and end) stations for the demographic
top_10_visits <- function(demographic, demo_type) { 

#number of demographic visits to each start station (N_start)
start_tally <- db %>%
  dbGetQuery(paste("
SELECT trips.start_station_id, sum(1) AS N_start
FROM citibike.trips
WHERE", demographic, "=",demo_type, " 
GROUP BY trips.start_station_id
ORDER BY N_start desc;"))

#number of demographic visits to each end station (N_end)
end_tally <- db %>%
  dbGetQuery(paste("
SELECT trips.end_station_id, sum(1) AS N_end
FROM citibike.trips
WHERE ", demographic, "=",demo_type, "
GROUP BY trips.end_station_id
ORDER BY N_end desc;"))

#join start_tally and end_tally in order to calculate the total number of visits
visits <- full_join(start_tally, end_tally, by = c("start_station_id" = "end_station_id"))

#replacing NA values with 0
visits$N_start[is.na(visits$N_start)] <- 0

#calculating total visits by women
visits <- visits %>%
  mutate(total_visits = N_start + N_end) %>%
  arrange(desc(total_visits)) %>%
  head(10) %>%

#getting lat, lon, and station name from station summary table
  left_join(station_summary, by = c("start_station_id" = "station_id")) %>%
  select(lat, lon, name, start_station_id, total_visits)
return(visits)
}

#querying by demographic
female_visits <- top_10_visits(demographic = "gender", demo_type = "2")
sub_visits <- top_10_visits(demographic = "user_type", demo_type = "'Subscriber'")
```

```{r}
#finding gender distribution of citibike subscribers
#14670034 is total number of subs 
#note: gender is only recorded for subs.
sub_gender <- db %>%
  dbGetQuery("
SELECT gender, sum(1) AS N, sum(1)/14670034 AS percent
FROM citibike.trips
WHERE gender != 0
GROUP BY gender;")
```

```{r}
trips <- dbGetQuery(db, "SELECT start_time, user_type
FROM citibike.trips;")
```

```{r}
hours_fun <- function(hour_arg, user_arg) {
  trips %>%
    mutate(new_start_time = str_extract(start_time, "[0-9]{2}\\:[0-9]{2}\\:[0-9]{2}")) %>%
    mutate(hour_time = grepl(paste("^", hour_arg, ":", sep =""), new_start_time)) %>%
    filter(hour_time == "TRUE") %>%
    filter(user_type == user_arg) %>%
    summarize(N = n())
}
hours_list <- c("00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23")
subscriber_hours <- lapply(hours_list, user_arg = "Subscriber", FUN = hours_fun) %>%
  bind_rows()
customer_hours <- lapply(hours_list, user_arg = "Customer", FUN = hours_fun) %>%
  bind_rows()

View(subscriber_hours)
View(customer_hours)
```

```{r}
hours_fun <- function(hour_arg) {
  trips %>%
    mutate(new_start_time = str_extract(start_time, "[0-9]{2}\\:[0-9]{2}\\:[0-9]{2}")) %>%
    mutate(hour_time = grepl(paste("^", hour_arg, ":", sep =""), new_start_time)) %>%
    filter(hour_time == "TRUE") %>%
    summarize(N = n())
}
hours_list <- c("00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23")
everyone_hours <- lapply(hours_list, FUN = hours_fun) %>%
  bind_rows()

View(everyone_hours)

```

```{r}
# Spatial data on Leaflet
female_visits <- top_10_visits(demographic = "gender", demo_type = "2")
sub_visits <- top_10_visits(demographic = "user_type", demo_type = "'Subscriber'")
male_visits <- top_10_visits(demographic = "gender", demo_type = "1")
cust_visits <- top_10_visits(demographic = "user_type", demo_type = "'Customer'")

female_visits_icons <- awesomeIcons(library = 'fa', icon = 'bicycle', markerColor = "red", iconColor = "ivory")
male_visits_icons <- awesomeIcons(library = 'fa', icon = 'bicycle', markerColor = "blue", iconColor = "ivory")
sub_visits_icons <- awesomeIcons(library = 'fa', icon = 'bicycle', markerColor = "orange", iconColor = "black") 
cust_visits_icons <- awesomeIcons(library = 'fa', icon = 'bicycle', markerColor = "darkpurple", iconColor = "ivory")
everyone_visits_icons <- awesomeIcons(library = 'fa', icon = 'bicycle', markerColor = "green", iconColor = "ivory")

leaflet() %>%
  addTiles() %>%
  addAwesomeMarkers(data = female_visits, popup = ~name, icon = female_visits_icons, group = "Top 10 Stations for Women") %>%
  addAwesomeMarkers(data = male_visits, popup = ~name, icon = male_visits_icons, group = "Top 10 Stations for Men") %>%
  addAwesomeMarkers(data = sub_visits, popup = ~name, icon = sub_visits_icons, group = "Top 10 Stations for Subscribers") %>%
  addAwesomeMarkers(data = cust_visits, popup = ~name, icon = cust_visits_icons, group = "Top 10 Stations for Customers") %>%
  addAwesomeMarkers(data = everyone_visits, popup = ~name, icon = everyone_visits_icons, group = "Top 10 Stations for Everyone") %>%
  addLegend("bottomright", colors = c("red", "blue", "orange", "purple", "green"), labels = c("Women", "Men", "Subscribers", "Customers", "Everyone")) %>%
  addLayersControl(overlayGroups = c("Top 10 Stations for Women", "Top 10 Stations for Men", "Top 10 Stations for Subscribers", "Top 10 Stations for Customers", "Top 10 Stations for Everyone"), options = layersControlOptions(collapsed = FALSE))
```



```{r}
#calculating tally of visits across all stations 
hours_fun <- function(hour_arg, demographic, demo_arg) {
  dbGetQuery(db, paste("
SELECT start_time, user_type, gender
FROM citibike.trips
WHERE", demographic, "=", demo_arg, ";")) %>%
    mutate(new_start_time = str_extract(start_time, "[0-9]{2}\\:[0-9]{2}\\:[0-9]{2}")) %>%
    mutate(hour_time = grepl(paste("^", hour_arg, ":", sep =""), new_start_time)) %>%
    filter(hour_time == "TRUE") %>%
    summarize(N = n())
}

hours_list <- c("00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23")

subscriber_hours <- lapply(hours_list, demographic = "user_type", demo_arg = "'Subscriber'", FUN = hours_fun) %>%
  bind_rows()
View(subscriber_hours)

customer_hours <- lapply(hours_list, demographic = "user_type", demo_arg = "'Customer'", FUN = hours_fun) %>%
  bind_rows()
View(customer_hours)

male_hours <- lapply(hours_list, demographic = "gender", demo_arg = "1", FUN = hours_fun) %>%
  bind_rows()
View(male_hours)

female_hours <- lapply(hours_list, demographic = "gender", demo_arg = "2", FUN = hours_fun) %>%
  bind_rows()
View(female_hours)
```

```{r}
list_hours <- c("12AM", "1AM", "2AM", "3AM", "4AM", "5AM", "6AM", "7AM", "8AM", "9AM", "10AM", "11AM", "12PM", "1PM", "2PM", "3PM", "4PM", "5PM", "6PM", "7PM", "8PM", "9PM", "10PM", "11PM")
female_hours$hours <-  list_hours
female_hours$hours <- factor(female_hours$hours, levels = list_hours)
ggplot(data = female_hours, aes(x = hours, y = N)) +
 geom_col()
male_hours$hours <-  list_hours
male_hours$hours <- factor(male_hours$hours, levels = list_hours)
ggplot(data = male_hours, aes(x = hours, y = N)) +
 geom_col()
customer_hours$hours <-  list_hours
customer_hours$hours <- factor(customer_hours$hours, levels = list_hours)
ggplot(data = customer_hours, aes(x = hours, y = N)) +
 geom_col()
subscriber_hours$hours <-  list_hours
subscriber_hours$hours <- factor(subscriber_hours$hours, levels = list_hours)
ggplot(data = subscriber_hours, aes(x = hours, y = N)) +
 geom_col()
```
